{"name": "Process a phone order and Cancel it", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\n +  where 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = order('Phone Order')\n +    where order = <logic.takeout_logic.Calculations object at 0x0000024E187B9300>.order\n +      where <logic.takeout_logic.Calculations object at 0x0000024E187B9300> = <test_cash.test_phoneorder_cash.TestPhoneOrderCash object at 0x0000024E187BAAD0>.phone", "trace": "self = <test_cash.test_phoneorder_cash.TestPhoneOrderCash object at 0x0000024E187BAAD0>\n\n    @allure.story(\"Phone Order Save and Cancel\")\n    @allure.title(\"Process a phone order and Cancel it\")\n    def test_phoneorder_cancel_order(self):\n    \n>       assert self.phone.order(\"Phone Order\") == True\nE       AssertionError: assert 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\nE        +  where 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = order('Phone Order')\nE        +    where order = <logic.takeout_logic.Calculations object at 0x0000024E187B9300>.order\nE        +      where <logic.takeout_logic.Calculations object at 0x0000024E187B9300> = <test_cash.test_phoneorder_cash.TestPhoneOrderCash object at 0x0000024E187BAAD0>.phone\n\nAutomation-logic\\suits\\test_orderflows\\test_cash\\test_phoneorder_cash.py:61: AssertionError"}, "start": 1742912407039, "stop": 1742912417739, "uuid": "4d38a111-4277-4dd5-969b-e8df52ccd52d", "historyId": "1d1d11021c7e82cda853b5086d6e9e1a", "testCaseId": "1d1d11021c7e82cda853b5086d6e9e1a", "fullName": "suits.test_orderflows.test_cash.test_phoneorder_cash.TestPhoneOrderCash#test_phoneorder_cancel_order", "labels": [{"name": "story", "value": "Phone Order Save and Cancel"}, {"name": "epic", "value": "Orderflow"}, {"name": "feature", "value": "Phone order in Cash"}, {"name": "parentSuite", "value": "suits.test_orderflows.test_cash"}, {"name": "suite", "value": "test_phoneorder_cash"}, {"name": "subSuite", "value": "TestPhoneOrderCash"}, {"name": "host", "value": "LAPTOP-KKMKONCC"}, {"name": "thread", "value": "15012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "suits.test_orderflows.test_cash.test_phoneorder_cash"}]}