{"name": "Process a phone order with cash payment and refund", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Error Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given search ...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\n +  where 'Error Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given search ...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = card_refund()\n +    where card_refund = <logic.takeout_logic.Calculations object at 0x00000232F1730F80>.card_refund\n +      where <logic.takeout_logic.Calculations object at 0x00000232F1730F80> = <test_phoneorder_card.TestPhoneOrderCard object at 0x00000232F3FD0890>.phone", "trace": "self = <test_phoneorder_card.TestPhoneOrderCard object at 0x00000232F3FD0890>\n\n    @allure.story(\"Phone Order Payment \")\n    @allure.title(\"Process a phone order with cash payment and refund\")\n    def test_phoneorder_card_payment(self):\n    \n        assert self.phone.order(\"Phone Order\") == True\n        assert self.phone.search_cust_phoneorder() == True\n        assert self.phone.add_multiple_items(2) is True\n    \n        assert self.phone.card_payment() == True\n    \n>       assert self.phone.card_refund() == True\nE       AssertionError: assert 'Error Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given search ...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\nE        +  where 'Error Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given search ...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = card_refund()\nE        +    where card_refund = <logic.takeout_logic.Calculations object at 0x00000232F1730F80>.card_refund\nE        +      where <logic.takeout_logic.Calculations object at 0x00000232F1730F80> = <test_phoneorder_card.TestPhoneOrderCard object at 0x00000232F3FD0890>.phone\n\nsuits\\test_orderflows\\test_card\\test_phoneorder_card.py:32: AssertionError"}, "start": 1741783657801, "stop": 1741783730832, "uuid": "3d82d56e-c072-42e2-8965-d1df1381df22", "historyId": "5a5bf354ee313e5d52feb75c5451716d", "testCaseId": "5a5bf354ee313e5d52feb75c5451716d", "fullName": "suits.test_orderflows.test_card.test_phoneorder_card.TestPhoneOrderCard#test_phoneorder_card_payment", "labels": [{"name": "story", "value": "Phone Order Payment "}, {"name": "feature", "value": "Sanity Sheet"}, {"name": "parentSuite", "value": "suits.test_orderflows.test_card"}, {"name": "suite", "value": "test_phoneorder_card"}, {"name": "subSuite", "value": "TestPhoneOrderCard"}, {"name": "host", "value": "LAPTOP-KKMKONCC"}, {"name": "thread", "value": "13720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "suits.test_orderflows.test_card.test_phoneorder_card"}]}