{"uuid": "f46c6c81-a9cd-4ea8-994d-77d6592a454d", "children": ["86a46db5-ac58-48f1-9d53-90479f809edd"], "befores": [{"name": "capture_screenshot_on_failure", "status": "passed", "start": 1743613695603, "stop": 1743613695603}], "afters": [{"name": "capture_screenshot_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\rutwik\\Automation\\Automation-logic\\conftest.py\", line 102, in capture_screenshot_on_failure\n    if request.node.rep_call.failed:\n"}, "start": 1743613806097, "stop": 1743613806143}], "start": 1743613695603, "stop": 1743613806143}