{"name": "Complete card payment", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Error Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given search ...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' is True\n +  where 'Error Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given search ...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = cash_pay()\n +    where cash_pay = <logic.takeout_logic.Calculations object at 0x0000018ADFC790C0>.cash_pay\n +      where <logic.takeout_logic.Calculations object at 0x0000018ADFC790C0> = <test_cash.test_takeoutorder_cash.TestTakeoutFlow object at 0x0000018ADFC7AE60>.calc", "trace": "self = <test_cash.test_takeoutorder_cash.TestTakeoutFlow object at 0x0000018ADFC7AE60>\n\n    @allure.story(\"Payment Processing\")\n    @allure.title(\"Complete card payment\")\n    def test_final_pay(self):\n        print(\"=================Cash Payment====================\")\n>       assert self.calc.cash_pay() is True\nE       AssertionError: assert 'Error Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given search ...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' is True\nE        +  where 'Error Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given search ...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = cash_pay()\nE        +    where cash_pay = <logic.takeout_logic.Calculations object at 0x0000018ADFC790C0>.cash_pay\nE        +      where <logic.takeout_logic.Calculations object at 0x0000018ADFC790C0> = <test_cash.test_takeoutorder_cash.TestTakeoutFlow object at 0x0000018ADFC7AE60>.calc\n\nAutomation-logic\\suits\\test_orderflows\\test_cash\\test_takeoutorder_cash.py:77: AssertionError"}, "start": 1742903524161, "stop": 1742903556794, "uuid": "d946e9d3-0c09-4149-aa6e-1ec7c834ba3e", "historyId": "a50ed728a8d93b9c8e6ff3f5b3ad97b1", "testCaseId": "a50ed728a8d93b9c8e6ff3f5b3ad97b1", "fullName": "suits.test_orderflows.test_cash.test_takeoutorder_cash.TestTakeoutFlow#test_final_pay", "labels": [{"name": "story", "value": "Payment Processing"}, {"name": "epic", "value": "Orderflow"}, {"name": "feature", "value": "Takeout order in Cash"}, {"name": "parentSuite", "value": "suits.test_orderflows.test_cash"}, {"name": "suite", "value": "test_takeoutorder_cash"}, {"name": "subSuite", "value": "TestTakeoutFlow"}, {"name": "host", "value": "LAPTOP-KKMKONCC"}, {"name": "thread", "value": "7416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "suits.test_orderflows.test_cash.test_takeoutorder_cash"}]}